### ISSUE TITLE
Hard to access rest of the UI beyond login page

### ISSUE THREAD

**Issue by ManayPatel** [alirabeea/teamoctave-course-organizer#15]
After creating an account using the signup page I was not able to log into it. This leaves me confused about whether the login was not working or the sign-up was not working.
Tried to take a quick glance through the documents and test code to see if I could find a dummy account to log into. Was not able to log in using the credentials: username: "foo", password: "bar".
Would be nice if you could document somewhere about a dummy account that anyone can log into.

**Comment by sallyrademacher** [comment]
dummy accound for now is both the username and password being "password" (no quotes when you input). will try to get that documented somewhere

**Comment by sallyrademacher** [comment]
You can now create an account and then log in with the credentials.
