### ISSUE TITLE
Tried to decode Graduation Requirements.json into array of requirements

### ISSUE THREAD

**Issue by nguyengangiang** [alirabeea/teamoctave-course-organizer#16]
Error when tried to run

keyNotFound(CodingKeys(stringValue: "id", intValue: nil), Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"id\", intValue: nil) (\"id\").", underlyingError: nil))

**Comment by sallyrademacher** [comment]
where are you trying to decode?

**Comment by nguyengangiang** [comment]
> where are you trying to decode?

I added the imported the json file for course info and graduation requirement, I'm trying to decode the graduation requirement first for the add requirement view

**Comment by sallyrademacher** [comment]
got it, Ill take a look
